import { StyleSheet, Platform } from "react-native";
export const colors = {
  primary: "#C20200",
  primaryDark: "#520600",
  primaryLight: "#E63946",
  success: "#2ECC71",
  warning: "#F39C12",
  danger: "#E74C3C",
  textDark: "#520600",
  textMedium: "#736F73",
  textLight: "#999999",
  white: "#FFFFFF",
  backgroundLight: "#F8F9FA",
  border: "#E0E0E0",
  shadowColor: "#000000",
};
export const tagColors = {
  red: { bg: "#FFE5E5", text: "#C20200", border: "#C20200" },
  pink: { bg: "#FCE4EC", text: "#AD1457", border: "#EC407A" },
  purple: { bg: "#F3E5F5", text: "#6A1B9A", border: "#AB47BC" },
  blue: { bg: "#E3F2FD", text: "#1565C0", border: "#42A5F5" },
  cyan: { bg: "#E0F7FA", text: "#00838F", border: "#26C6DA" },
  teal: { bg: "#E0F2F1", text: "#00695C", border: "#26A69A" },
  green: { bg: "#E8F5E9", text: "#2E7D32", border: "#66BB6A" },
  lime: { bg: "#F9FBE7", text: "#827717", border: "#D4E157" },
  yellow: { bg: "#FFFDE7", text: "#F57F17", border: "#FFEE58" },
  orange: { bg: "#FFF3E0", text: "#E65100", border: "#FFA726" },
  brown: { bg: "#EFEBE9", text: "#4E342E", border: "#8D6E63" },
  gray: { bg: "#F5F5F5", text: "#424242", border: "#9E9E9E" },
};
export const getTagColor = (tag: string): typeof tagColors.red => {
  const tagLower = tag.toLowerCase();
  if (tagLower.includes("sale") || tagLower.includes("deal")) return tagColors.red;
  if (tagLower.includes("health") || tagLower.includes("organic")) return tagColors.green;
  if (tagLower.includes("snack") || tagLower.includes("treat")) return tagColors.pink;
  if (tagLower.includes("weekly") || tagLower.includes("daily")) return tagColors.blue;
  if (tagLower.includes("party") || tagLower.includes("celebration")) return tagColors.purple;
  if (tagLower.includes("clean") || tagLower.includes("household")) return tagColors.cyan;
  if (tagLower.includes("beverage") || tagLower.includes("drink")) return tagColors.orange;
  if (tagLower.includes("grocery") || tagLower.includes("essential")) return tagColors.teal;
  const hash = tag.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
  const colorKeys = Object.keys(tagColors) as Array<keyof typeof tagColors>;
  const colorKey = colorKeys[hash % colorKeys.length];
  return tagColors[colorKey];
};
export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
};
export const safeAreaPadding = {
  bottom: {
    ios: 34,
    android: 16,
  },
};
export const borderRadius = {
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  round: 999,
};
export const elevation = {
  sm: {
    shadowColor: colors.shadowColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  md: {
    shadowColor: colors.shadowColor,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  lg: {
    shadowColor: colors.shadowColor,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 6,
  },
};
export const typography = {
  h1: {
    fontSize: 32,
    fontWeight: "700" as const,
    letterSpacing: 0.5,
    lineHeight: 40,
  },
  h2: {
    fontSize: 24,
    fontWeight: "700" as const,
    letterSpacing: 0.4,
    lineHeight: 32,
  },
  h3: {
    fontSize: 20,
    fontWeight: "600" as const,
    letterSpacing: 0.3,
    lineHeight: 28,
  },
  body: {
    fontSize: 16,
    fontWeight: "400" as const,
    letterSpacing: 0.2,
    lineHeight: 24,
  },
  bodyBold: {
    fontSize: 16,
    fontWeight: "600" as const,
    letterSpacing: 0.2,
    lineHeight: 24,
  },
  bodySmall: {
    fontSize: 14,
    fontWeight: "400" as const,
    letterSpacing: 0.2,
    lineHeight: 20,
  },
  caption: {
    fontSize: 12,
    fontWeight: "400" as const,
    letterSpacing: 0.1,
    lineHeight: 16,
  },
  button: {
    fontSize: 16,
    fontWeight: "600" as const,
    letterSpacing: 0.3,
  },
};
export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: spacing.xl,
    backgroundColor: colors.white,
    justifyContent: "center",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.white,
  },
  safeArea: {
    flex: 1,
    backgroundColor: "transparent",
  },
  scrollContent: {
    padding: spacing.xl,
    paddingBottom: spacing.xxxl,
  },
  scrollContentWithBottomBar: {
    padding: spacing.xl,
    paddingBottom: 120,
  },
  formWrapper: {
    paddingHorizontal: spacing.xxl,
    width: "100%",
    maxWidth: 500,
    alignSelf: "center",
  },
  headerContainer: {
    marginBottom: spacing.md,
  },
  greetingText: {
    ...typography.h1,
    color: colors.textDark,
  },
  dateText: {
    ...typography.body,
    color: colors.textMedium,
    marginTop: spacing.sm,
  },
  titleText: {
    ...typography.h1,
    color: colors.primary,
    marginBottom: spacing.xxl,
    textAlign: "center",
  },
  headerTitle: {
    ...typography.h2,
    color: colors.primary,
    marginBottom: spacing.lg,
    textAlign: "center",
  },
  sectionTitle: {
    ...typography.h3,
    color: colors.primary,
    marginBottom: spacing.lg,
  },
  footerText: {
    ...typography.bodySmall,
    marginTop: spacing.xl,
    textAlign: "center",
    color: colors.textMedium,
  },
  footerLink: {
    color: colors.primary,
    fontWeight: "600",
  },
  statsCard: {
    marginBottom: spacing.xxl,
    padding: spacing.xl,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.white,
    shadowColor: colors.shadowColor,
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
    borderWidth: 1,
    borderColor: colors.border,
  },
  statsTitle: {
    ...typography.h3,
    marginBottom: spacing.md,
    color: colors.textDark,
  },
  statsText: {
    ...typography.body,
    color: colors.textMedium,
    marginBottom: spacing.sm,
  },
  optionsText: {
    ...typography.h3,
    color: colors.textDark,
    marginBottom: spacing.xl,
  },
  optionsContainer: {
    gap: spacing.lg,
  },
  previousBuysButton: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.xl,
    padding: spacing.xxl,
    borderWidth: 2,
    borderColor: colors.primary,
    shadowColor: colors.shadowColor,
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  previousBuysTitle: {
    ...typography.h3,
    fontSize: 20,
    color: colors.primary,
    marginBottom: spacing.sm,
  },
  previousBuysSubtitle: {
    ...typography.body,
    color: colors.textMedium,
    lineHeight: 22,
  },
  newListButton: {
    backgroundColor: colors.primary,
    borderRadius: borderRadius.xl,
    padding: spacing.xxl,
    shadowColor: colors.shadowColor,
    shadowOpacity: 0.15,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  newListTitle: {
    ...typography.h3,
    fontSize: 20,
    color: colors.white,
    marginBottom: spacing.sm,
  },
  newListSubtitle: {
    ...typography.body,
    color: "#f0f0f0",
    lineHeight: 22,
  },
  inputField: {
    height: 48,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.lg,
    fontSize: 16,
    backgroundColor: colors.backgroundLight,
    color: colors.textDark,
    ...elevation.sm,
  },
  inputFieldFocused: {
    borderWidth: 2,
    borderColor: colors.primary,
    backgroundColor: colors.white,
  },
  buttonContainer: {
    backgroundColor: colors.primary,
    paddingVertical: 16,
    paddingHorizontal: spacing.xxl,
    borderRadius: borderRadius.md,
    alignItems: "center",
    justifyContent: "center",
    marginTop: spacing.sm,
    shadowColor: colors.shadowColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    minHeight: 56,
    minWidth: 100,
  },
  buttonContainerSecondary: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.primary,
  },
  buttonContainerSuccess: {
    backgroundColor: colors.success,
  },
  buttonContainerWarning: {
    backgroundColor: colors.warning,
  },
  buttonContainerDanger: {
    backgroundColor: colors.danger,
  },
  buttonText: {
    ...typography.button,
    color: colors.white,
  },
  buttonTextSecondary: {
    color: colors.primary,
  },
  linkButton: {
    paddingVertical: spacing.md,
    alignItems: "center",
  },
  linkButtonText: {
    ...typography.button,
    color: colors.primary,
  },
});
export const createScreenStyles = StyleSheet.create({
  sectionLabel: {
    ...typography.h3,
    fontSize: 16,
    color: colors.textDark,
    marginBottom: spacing.md,
    fontWeight: "600",
  },
  deleteButtonContainer: {
    justifyContent: "center",
    alignItems: "flex-end",
    marginBottom: 12,
  },
  deleteButton: {
    backgroundColor: colors.danger,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    paddingHorizontal: spacing.lg,
    height: 48,
    borderRadius: borderRadius.md,
    marginLeft: spacing.sm,
    minWidth: 100,
    ...elevation.md,
  },
  deleteButtonText: {
    ...typography.bodyBold,
    color: colors.white,
    marginLeft: spacing.xs,
  },
  suggestionsContainer: {
    backgroundColor: colors.white,
    borderColor: colors.border,
    borderWidth: 1.5,
    borderTopWidth: 0,
    borderBottomLeftRadius: borderRadius.md,
    borderBottomRightRadius: borderRadius.md,
    marginTop: -spacing.sm,
    shadowColor: colors.shadowColor,
    shadowOpacity: 0.15,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
    maxHeight: 160,
    overflow: "hidden",
  },
  suggestionItem: {
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderBottomColor: colors.border,
    borderBottomWidth: 0.5,
    backgroundColor: colors.white,
    minHeight: 48,
  },
  suggestionText: {
    ...typography.body,
    color: colors.textDark,
    fontWeight: "500",
  },
  bottomBar: {
    position: "absolute" as const,
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: "row",
    backgroundColor: colors.white,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: Platform.OS === "ios" ? spacing.lg : spacing.md,
    borderTopWidth: 1,
    borderColor: colors.border,
    gap: spacing.sm,
    shadowColor: colors.shadowColor,
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: -2 },
    elevation: 8,
  },
  bottomButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: spacing.xs,
    borderRadius: borderRadius.sm,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
  },
  colorOption: {
    width: 56,
    height: 56,
    borderRadius: borderRadius.md,
    marginRight: spacing.md,
    marginBottom: spacing.md,
    borderWidth: 2,
  },
  colorOptionSelected: {
    borderWidth: 3,
    borderColor: colors.textDark,
  },
  colorOptionUnselected: {
    borderColor: colors.border,
  },
});
export const previousListStyles = StyleSheet.create({
  topSection: {
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xl,
    paddingBottom: spacing.md,
    backgroundColor: colors.white,
    flexShrink: 0,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  shareCodeContainer: {
    flexDirection: "row",
    marginBottom: spacing.lg,
    gap: spacing.sm,
  },
  shareCodeInput: {
    flex: 1,
    borderColor: colors.primary,
    borderWidth: 1.5,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    fontSize: 16,
    height: 52,
    backgroundColor: colors.backgroundLight,
  },
  shareCodeButton: {
    backgroundColor: colors.primary,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.xl,
    justifyContent: "center",
    minWidth: 80,
    minHeight: 52,
    shadowColor: colors.shadowColor,
    shadowOpacity: 0.15,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  shareCodeButtonText: {
    ...typography.button,
    color: colors.white,
  },
  tagsFilterContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: spacing.lg,
    gap: spacing.sm,
    alignItems: "center",
  },
  tagButton: {
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: borderRadius.xl,
    borderWidth: 1.5,
    borderColor: colors.primary,
    backgroundColor: "transparent",
    minHeight: 32,
  },
  tagButtonSelected: {
    backgroundColor: colors.primary,
  },
  tagButtonText: {
    ...typography.bodySmall,
    color: colors.primary,
    fontWeight: "600",
  },
  tagButtonTextSelected: {
    color: colors.white,
  },
  listsScrollView: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
  },
  listCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.md,
    borderWidth: 2,
    marginBottom: spacing.lg,
    padding: spacing.lg,
    ...elevation.md,
  },
  listCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  listTitle: {
    ...typography.h3,
    fontSize: 18,
    flex: 1,
  },
  listCardButtons: {
    flexDirection: "row",
    gap: spacing.lg,
  },
  tagsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: spacing.sm,
    gap: spacing.xs,
  },
  tagBadge: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.xl,
    borderWidth: 1.5,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  tagBadgeText: {
    fontSize: 12,
    fontWeight: "600",
  },
  tagColorDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  actionButton: {
    alignItems: "center",
    padding: spacing.sm,
  },
  actionButtonText: {
    fontSize: 10,
    marginTop: spacing.xs,
    fontWeight: "600",
  },
});
export const onboardingStyles = StyleSheet.create({
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.md,
    paddingBottom: spacing.lg,
  },
  headerLogo: {
    width: 50,
    height: 50,
    resizeMode: "contain",
  },
  skipButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.md,
    backgroundColor: colors.primary + "10",
  },
  skipContainer: {
    alignItems: "flex-end",
    paddingHorizontal: spacing.xxl,
    paddingTop: spacing.md,
  },
  skipText: {
    ...typography.button,
    color: colors.primary,
    fontWeight: "600",
  },
  contentWrapper: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: spacing.xl,
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.xl,
    padding: spacing.xxxl,
    alignItems: "center",
    ...elevation.md,
    width: "100%",
    maxWidth: 400,
    borderWidth: 1,
    borderColor: colors.border,
  },
  iconContainer: {
    marginBottom: spacing.xxl,
  },
  iconGradient: {
    width: 120,
    height: 120,
    borderRadius: 60,
    justifyContent: "center",
    alignItems: "center",
    ...elevation.lg,
  },
  image: {
    width: 100,
    height: 100,
    marginBottom: spacing.xl,
    resizeMode: "contain",
  },
  title: {
    ...typography.h2,
    color: colors.textDark,
    marginBottom: spacing.md,
    textAlign: "center",
    fontWeight: "700",
  },
  description: {
    ...typography.body,
    color: colors.textMedium,
    textAlign: "center",
    paddingHorizontal: spacing.sm,
    lineHeight: 24,
    fontSize: 16,
  },
  dotsContainer: {
    flexDirection: "row",
    justifyContent: "center",
    gap: spacing.sm,
    marginTop: spacing.xl,
    marginBottom: spacing.md,
  },
  dots: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: spacing.xxl,
    marginTop: spacing.md,
    gap: spacing.sm,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  bottomSection: {
    paddingHorizontal: spacing.xl,
    paddingBottom: Platform.OS === "ios" ? spacing.xxxl : spacing.xl,
    gap: spacing.lg,
  },
  progressContainer: {
    gap: spacing.sm,
  },
  progressText: {
    fontSize: 13,
    color: colors.textMedium,
    fontWeight: "600",
    textAlign: "center",
  },
  progressBar: {
    height: 4,
    backgroundColor: colors.backgroundLight,
    borderRadius: borderRadius.sm,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: colors.primary,
    borderRadius: borderRadius.sm,
  },
  nextButton: {
    backgroundColor: colors.primary,
    borderRadius: borderRadius.lg,
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.xl,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    ...elevation.md,
    minHeight: 56,
  },
  nextButtonText: {
    ...typography.button,
    color: colors.white,
    fontSize: 17,
    fontWeight: "700",
  },
});
